spring.application.name=airBnbApp

spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb
spring.datasource.username=postgres
spring.datasource.password=Ayush@2001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.properties.format_sql=true

server.servlet.context-path=/api/v1

jwt.secretKey=ajjdheieiryrru48737774929727472dcbsjfgrr7863245hf

frontend.url=http://localhost:8080
stripe.secret.key=sk_test_51TRdlX1sp2zmlIQuGFUBKBvayNamPL9U5Hu25ufyuyfefUtI6A73xgFfY5FRAl1xUbfgBu7lFHF3ShzK81tgrYbL00VdPXnkCt
stripe.webhook.secret=whsec_8a334ec01bcc7b6c596385e5928af49237b4609620c85c181861793b22ac91f9